export const TeamMembers = [
  {
    id: "1",
    name: "Dr. Devendra Deshmukh ",
    position: "Advisor",
    email: " ",
    linkedin: "https://www.linkedin.com/in/dalalbhavya",
    github: "https://github.com/dalalbhavya",
  },
  {
    id: "2",
    name: "Bhavya Dalal",
    position: "Member",
    email: "me200003020@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "3",
    name: "Kshitij M Bhat",
    position: "Member",
    email: "me200003042@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/raghuvamsi-bokka-572307225/",
    github: "https://github.com/Vamsi-IITI",
  },
  {
    id: "4",
    name: "Raghuvamsi Bokka",
    position: "Member",
    email: "me200003062@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "5",
    name: "Jitendra Kumar Choudhary",
    position: "Member",
    email: "me200003037@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "6",
    name: "K Vishnu Vardhan",
    position: "Member",
    email: "me200002042@iiti.ac.in",
    linkedin: "linkedin.com/in/yeeshukant-singh-47845a200",
    github: "https://github.com/Yeeshukant",
  },
  {
    id: "7",
    name: "Yeeshukant Singh",
    position: "Member",
    email: "ee200002082@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/atharva-tayshete-028622169",
    github: "https://github.com/atharvact02",
  },
  {
    id: "8",
    name: "Atharva Tayshete",
    position: "Member",
    email: "ee200002016@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "9",
    name: "Karandevsinh Khuman",
    position: "Member",
    email: "ee200002044@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "10",
    name: "Vihaan Thora",
    position: "Member",
    email: "cse200001079@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "11",
    name: "Jaydeep Umarya",
    position: "Member",
    email: "me200003035@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/het-sekhalia-a1a0b8226",
    github: "https://github.com/Het4799",
  },
  {
    id: "12",
    name: "Het Sekhalia",
    position: "Member",
    email: "me200003032@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "13",
    name: "Varade Tejas Deelip",
    position: "Member",
    email: "me200003082@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "14",
    name: "Srijan Parashar",
    position: "Member",
    email: "me200003073@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "15",
    name: "Puneet Gupta",
    position: "Member",
    email: "me200003060@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "16",
    name: "Abiroop Mohan",
    position: "Member",
    email: "ee210002004@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "17",
    name: "Aditya Guhagarkar",
    position: "Member",
    email: "ee210002005@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "18",
    name: "Akshit Raizada",
    position: "Member",
    email: "me210003009@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/akshit-raizada",
    github: "https://github.com/AkshitRaizada",
  },
  {
    id: "19",
    name: "Sairaj Loke",
    position: "Member",
    email: "cse210001035@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/sairaj-loke-24370b237",
    github: "https://github.com/SairajLoke",
  },
  {
    id: "20",
    name: "Prakhar Goel",
    position: "Member",
    email: "ee210002058@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/prakhar-goel02",
    github: "https://github.com/pgoel02",
  },
  {
    id: "21",
    name: "Soham Mondal",
    position: "Member",
    email: "me210003071@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "22",
    name: "Sarthak Agarwal",
    position: "Member",
    email: " ",
    linkedin: " ",
    github: " ",
  },
  {
    id: "23",
    name: "Vedant Badoniya",
    position: "Member",
    email: " ",
    linkedin: " ",
    github: " ",
  },
  {
    id: "24",
    name: "Utkarsh Pandey",
    position: "Member",
    email: "me210003080@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "25",
    name: "Aditya Suwalka",
    position: "Member",
    email: "me210003008@iiti.ac.in",
    linkedin: " ",
    github: "https://github.com/git-suwalkaaditya",
  },
  {
    id: "26",
    name: "Abhishek Nair",
    position: "Member",
    email: "me210003005@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/abhisheknair14",
    github: "https://github.com/NairAbhishek1403",
  },
  {
    id: "27",
    name: "Jugal Shah",
    position: "Member",
    email: "me210003040@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "28",
    name: "Sachin Sahu",
    position: "Member",
    email: "me210003064@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "29",
    name: "Harshit Kumar Singh",
    position: "Member",
    email: "me210003036@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "30",
    name: "Om Patel",
    position: "Member",
    email: "me210003051@iiti.ac.in",
    linkedin: " ",
    github: " ",
  },
  {
    id: "31",
    name: "Soham Pandit",
    position: "Member",
    email: "me220003080@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/soham-pandit-379b35255",
    github: "https://github.com/Scav6411",
  },
  {
    id: "32",
    name: "Sameer Lakkad",
    position: "Member",
    email: "me220003071@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/sameer-lakkad-345667250/",
    github: "https://github.com/sameerlakkad",
  },
  {
    id: "33",
    name: "Yash Yewale",
    position: "Member",
    email: "me220003087@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/yash-yewale-29a453256",
    github: "https://github.com/yashy-163",
  },
  {
    id: "34",
    name: "Hrishikesh Hiremath",
    position: "Member",
    email: "me220003037@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/hrishikesh-hiremath",
    github: "https://github.com/Hrishikesh-H",
  },
  {
    id: "35",
    name: "Rakshit Jangid",
    position: "Member",
    email: "ee220002068@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/rakshit-jangid-5077a9253/",
    github: "https://github.com/rakshitjangid22",
  },
  {
    id: "36",
    name: "Nehansh Mankad",
    position: "Member",
    email: "ee220002050@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/mankad-nehansh-8a837a25a",
    github: " ",
  },
  {
    id: "37",
    name: "Giridhar A P",
    position: "Member",
    email: "ee220002033@iiti.ac.in",
    linkedin: "www.linkedin.com/in/giridhar-a-p-ak47",
    github: "https://github.com/Giri-is-coding",
  },
  {
    id: "38",
    name: "Bhawna Chaudhary",
    position: "Member",
    email: "ee22002027@iiti.ac.in",
    linkedin: "linkedin_link",
    github: "https://github.com/WebWizard104",
  },
  {
    id: "39",
    name: "K. Niketh Reddy",
    position: "Member",
    email: "cse220001040@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/niketh-reddy-k-42948b259/",
    github: "https://github.com/niketh457",
  },
  {
    id: "40",
    name: "Pranav Deshpande",
    position: "Member",
    email: "me220003062@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/pranav-deshpande-5391b725b/",
    github: "https://github.com/PDp04",
  },
  {
    id: "41",
    name: "Charan Amara",
    position: "Member",
    email: "me220003007@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/charan-amara-91302725b",
    github: "https://github.com/Charanamara",
  },
  {
    id: "42",
    name: "Mihir Hemani",
    position: "Member",
    email: "me220003052@iiti.ac.in",
    linkedin: "https://www.linkedin.com/in/mihir-hemani-a56638263/",
    github: " ",
  },
];
